### HEALTH CHECK
GET http://localhost:3001/health

### REGISTER USER
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test22223213",
  "password": "test12321345@312S",
  "email": "test223221@user.com"
}

### LOGIN USER
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "amirns",
  "password": "amir1995@!"
}