### HEALTH CHECK
GET http://localhost:3001/api/health

### REGISTER USER
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test45-1",
  "password": "tesAt1@123",
  "email": "test@6ser.com"
}

### LOGIN USER
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "test45-1",
  "password": "tesAt1@123"
}

### CHECK AUTHORIZATION
GET http://localhost:3001/api/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjA0YmExOGQ5LTc0YmYtNGFiOC05ZWI2LWJiM2VhOWMwZGRjZCIsImVtYWlsIjoidGVzdEA2c2VyLmNvbSIsInVzZXJuYW1lIjoidGVzdDQ1LTEiLCJpYXQiOjE3NTU0Mzc4MDYsImV4cCI6MTc1NTQzOTYwNn0.5rrZMu6OusnAsHYLunAvAEwsX5C7Hsv1M-uditcmdnA
